name: OrderApp - Publish Version

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-test-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore OrderApp.sln

      - name: Build solution
        run: dotnet build OrderApp.sln --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test OrderApp.sln --configuration Release --no-build --verbosity normal

      - name: Install coverage tools
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Run tests with coverage
        run: dotnet test OrderApp.sln --configuration Release --no-build --collect:"XPlat Code Coverage" --results-directory ./coverage

      - name: Generate coverage report
        run: |
          reportgenerator -reports:./coverage/**/coverage.cobertura.xml -targetdir:./coveragereport -reporttypes:"Html;MarkdownSummaryGithub"
          cat ./coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY

      - name: Publish coverage to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coveragereport
          destination_dir: coverage
          keep_files: true

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            src/OrderApp/bin/Release/net7.0/OrderApp.dll
            src/OrderApp/bin/Release/net7.0/OrderApp.pdb
          body: |
            ## OrderApp Release
            
            ### Cambios en esta versión
            - Implementación del patrón Builder
            - Pruebas unitarias con cobertura completa
            - Documentación completa con DocFX
            
            ### Archivos incluidos
            - OrderApp.dll - Biblioteca principal
            - OrderApp.pdb - Símbolos de depuración
            
            ### Cobertura de pruebas
            Ver el reporte completo en: https://upt-faing-epis.github.io/examen-si889-2025-ii-u2-Brunoenr02/coverage/
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./coveragereport
